### ISSUE TITLE
How about react native compatibility?

### ISSUE THREAD

**Issue by Misaka-0x447f** [nowaalex/af-utils#18]

**Comment by nowaalex** [comment]
Not yet done/tested, would be nice feature to have. PRs are welcome)

**Comment by Misaka-0x447f** [comment]
Got it. Feeling sorry that I don’t have much time to contribute in current stage of my life (and maybe it’s hard to achieve better performance than the official component [“flatlist”](https://reactnative.dev/docs/flatlist) without special native code.)
