### ISSUE TITLE
Manually scrolling causes scroll bar to become unaligned with mouse position

### ISSUE THREAD

**Issue by syllith** [nowaalex/af-utils#27]
When scrolling up and down manually by clicking and dragging the scroll bar, the position of the scroll bar becomes unaligned with the mouses position

**Comment by syllith** [comment]
Looks like the scroll wheel issue has been resolved by updating chrome! Thanks for letting me know. Still having the scrolling issue mentioned in my initial message, but it's a fairly small priority problem.

**Comment by syllith** [comment]
So sorry for the late response. Here is the screencast you requested. Hopefully this demonstrates what I mean. It's a fairly minor issue, but an issue I run into quite often. 
![screen-capture](https://user-images.githubusercontent.com/42996651/177532127-b823a064-cad0-4c3c-b326-987540d9cdc2.gif)

**Comment by nowaalex** [comment]
[new faq](https://af-utils.vercel.app/virtual/faq#why-cursor-and-scrollbar-become-unaligned-after-manual-scrolling)
